/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ares/{ic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Načti data subjektu z ARES podle IČO */
        get: operations["get-ares-subject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Přihlášený uživatel */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zdravotní stav služby */
        get: operations["get-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seznam faktur */
        get: operations["list-invoices"];
        put?: never;
        /** Vytvoř novou fakturu */
        post: operations["create-invoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail faktury */
        get: operations["get-invoice"];
        /** Aktualizuj fakturu */
        put: operations["update-invoice"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplikuj fakturu (nové číslo a datum) */
        post: operations["duplicate-invoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Změň stav faktury */
        patch: operations["patch-invoice-status"];
        trace?: never;
    };
    "/price-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seznam ceníkových položek */
        get: operations["list-price-items"];
        put?: never;
        /** Vytvoř ceníkovou položku */
        post: operations["create-price-item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail ceníkové položky */
        get: operations["get-price-item"];
        /** Aktualizuj ceníkovou položku */
        put: operations["update-price-item"];
        post?: never;
        /** Archivuj ceníkovou položku */
        delete: operations["archive-price-item"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price-items/{id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skladové pohyby položky */
        get: operations["list-stock-movements"];
        put?: never;
        /** Přidej ruční skladový pohyb */
        post: operations["create-stock-movement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Načti nastavení účtu */
        get: operations["get-settings"];
        /** Aktualizuj nastavení účtu */
        put: operations["update-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/number-formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seznam číselných řad */
        get: operations["list-number-formats"];
        put?: never;
        /** Vytvoř číselnou řadu */
        post: operations["create-number-format"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/number-formats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Aktualizuj číselnou řadu */
        put: operations["update-number-format"];
        post?: never;
        /** Smaž číselnou řadu */
        delete: operations["delete-number-format"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/number-formats/{id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vygeneruj další číslo dokladu */
        post: operations["next-number-format"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seznam kontaktů */
        get: operations["list-subjects"];
        put?: never;
        /** Vytvoř nový kontakt */
        post: operations["create-subject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail kontaktu */
        get: operations["get-subject"];
        /** Aktualizuj kontakt */
        put: operations["update-subject"];
        post?: never;
        /** Smaž kontakt */
        delete: operations["delete-subject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seznam uživatelů (superadmin) */
        get: operations["list-users"];
        put?: never;
        /** Vytvoř uživatele (superadmin) */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail uživatele (superadmin) */
        get: operations["get-user"];
        /** Aktualizuj uživatele (superadmin) */
        put: operations["update-user"];
        post?: never;
        /** Smaž uživatele (superadmin) */
        delete: operations["delete-user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset hesla (superadmin) */
        post: operations["reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateUserInputBody.json
             */
            readonly $schema?: string;
            email?: string;
            password: string;
            role?: string;
            username: string;
        };
        DeletedAt: {
            /** Format: date-time */
            Time: string;
            Valid: boolean;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @description Byl dokončen první setup */
            initialized: boolean;
            /** @description Je zapnutý multi-user mód */
            multi_user: boolean;
            /**
             * @description Stav služby
             * @example ok
             */
            status: string;
            /**
             * @description Verze API
             * @example 1.0.0
             */
            version: string;
        };
        Invoice: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Invoice.json
             */
            readonly $schema?: string;
            bank_account: string;
            client_city: string;
            client_country: string;
            client_delivery_city: string;
            client_delivery_country: string;
            client_delivery_name: string;
            client_delivery_street: string;
            client_delivery_zip: string;
            client_has_delivery_address: boolean;
            client_name: string;
            client_registration_no: string;
            client_street: string;
            client_vat_no: string;
            client_zip: string;
            /** Format: date-time */
            created_at: string;
            currency: string;
            custom_id: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            document_type: string;
            /** Format: int64 */
            due: number;
            exchange_rate: string;
            footer_note: string;
            iban: string;
            /** Format: int64 */
            id: number;
            issued_on: string;
            language: string;
            lines: components["schemas"]["InvoiceLine"][];
            note: string;
            number: string;
            order_number: string;
            paid_on?: string;
            payment_method: string;
            private_note: string;
            status: string;
            /** Format: int64 */
            subject_id?: number;
            /** Format: int64 */
            subtotal: number;
            swift_bic: string;
            tags: string;
            taxable_fulfillment_due: string;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            total_vat_hal: number;
            transferred_tax_liability: boolean;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            user_id?: number;
            variable_symbol: string;
            vat_exempt: boolean;
            vat_price_mode: string;
            your_city: string;
            your_country: string;
            your_name: string;
            your_registration_no: string;
            your_street: string;
            your_vat_no: string;
            your_zip: string;
        };
        InvoiceInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InvoiceInput.json
             */
            readonly $schema?: string;
            bank_account?: string;
            client_city?: string;
            client_country?: string;
            client_delivery_city?: string;
            client_delivery_country?: string;
            client_delivery_name?: string;
            client_delivery_street?: string;
            client_delivery_zip?: string;
            client_has_delivery_address?: boolean;
            client_name: string;
            client_registration_no?: string;
            client_street?: string;
            client_vat_no?: string;
            client_zip?: string;
            currency?: string;
            custom_id?: string;
            document_type?: string;
            /** Format: int64 */
            due?: number;
            exchange_rate?: string;
            footer_note?: string;
            iban?: string;
            issued_on: string;
            language?: string;
            lines: components["schemas"]["LineInput"][];
            note?: string;
            number: string;
            order_number?: string;
            payment_method?: string;
            private_note?: string;
            /** Format: int64 */
            subject_id?: number;
            swift_bic?: string;
            tags?: string;
            taxable_fulfillment_due: string;
            transferred_tax_liability?: boolean;
            variable_symbol?: string;
            vat_exempt?: boolean;
            vat_price_mode?: string;
            your_city?: string;
            your_country?: string;
            your_name?: string;
            your_registration_no?: string;
            your_street?: string;
            your_vat_no?: string;
            your_zip?: string;
        };
        InvoiceLine: {
            /** Format: date-time */
            created_at: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            invoice_id: number;
            name: string;
            /** Format: int64 */
            position: number;
            /** Format: int64 */
            price_item_id?: number;
            quantity: string;
            /** Format: int64 */
            total_hal: number;
            /** Format: int64 */
            total_price_without_vat_hal: number;
            /** Format: int64 */
            total_vat_hal: number;
            unit_name: string;
            /** Format: int64 */
            unit_price_hal: number;
            /** Format: int64 */
            unit_price_with_vat_hal: number;
            /** Format: int64 */
            unit_price_without_vat_hal: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: int32 */
            vat_rate_bps: number;
        };
        LineInput: {
            name: string;
            /** Format: int64 */
            position?: number;
            /** Format: int64 */
            price_item_id?: number;
            quantity?: string;
            unit_name?: string;
            /** Format: int64 */
            unit_price_hal: number;
            /** Format: int32 */
            vat_rate_bps?: number;
        };
        Lookup: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Lookup.json
             */
            readonly $schema?: string;
            city: string;
            country_code: string;
            dic: string;
            ic: string;
            name: string;
            street: string;
            zip: string;
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            email?: string;
            /** Format: int64 */
            id: number;
            role: string;
            username: string;
        };
        NextFormatOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NextFormatOutputBody.json
             */
            readonly $schema?: string;
            number: string;
        };
        NumberFormat: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NumberFormat.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            document_type: string;
            /** Format: int64 */
            id: number;
            label: string;
            /** Format: int64 */
            next_number: number;
            /** Format: int64 */
            padding_width: number;
            pattern: string;
            /** Format: int64 */
            settings_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        NumberFormatInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NumberFormatInput.json
             */
            readonly $schema?: string;
            document_type?: string;
            label?: string;
            /** Format: int64 */
            next_number?: number;
            /** Format: int64 */
            padding_width?: number;
            pattern?: string;
        };
        PatchStatusInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PatchStatusInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            status: "open" | "paid";
        };
        PriceItemInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PriceItemInput.json
             */
            readonly $schema?: string;
            allow_negative_stock?: boolean;
            catalog_no?: string;
            ean?: string;
            name: string;
            track_stock?: boolean;
            unit_name?: string;
            /** Format: int64 */
            unit_price_hal: number;
            /** Format: int32 */
            vat_rate_bps?: number;
        };
        PriceItemOut: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PriceItemOut.json
             */
            readonly $schema?: string;
            allow_negative_stock: boolean;
            archived: boolean;
            catalog_no?: string;
            /** Format: date-time */
            created_at: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            ean?: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: double */
            stock_quantity: number;
            track_stock: boolean;
            unit_name: string;
            /** Format: int64 */
            unit_price_hal: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            user_id?: number;
            /** Format: int32 */
            vat_rate_bps: number;
        };
        ResetPasswordInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ResetPasswordInputBody.json
             */
            readonly $schema?: string;
            password: string;
        };
        Settings: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Settings.json
             */
            readonly $schema?: string;
            bank_account: string;
            company_city: string;
            company_country: string;
            company_name: string;
            company_street: string;
            company_zip: string;
            /** Format: date-time */
            created_at: string;
            default_currency: string;
            /** Format: int64 */
            default_due: number;
            default_note: string;
            default_payment_method: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            iban: string;
            /** Format: int64 */
            id: number;
            invoice_template: string;
            number_formats: components["schemas"]["NumberFormat"][];
            registration_no: string;
            swift_bic: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            user_id?: number;
            vat_exempt: boolean;
            vat_no: string;
        };
        SettingsInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SettingsInput.json
             */
            readonly $schema?: string;
            bank_account?: string;
            company_city?: string;
            company_country?: string;
            company_name?: string;
            company_street?: string;
            company_zip?: string;
            default_currency?: string;
            /** Format: int64 */
            default_due?: number;
            default_note?: string;
            default_payment_method?: string;
            iban?: string;
            invoice_template?: string;
            registration_no?: string;
            swift_bic?: string;
            vat_exempt?: boolean;
            vat_no?: string;
        };
        StockMovement: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StockMovement.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            invoice_id?: number;
            note?: string;
            /** Format: int64 */
            price_item_id: number;
            quantity: string;
            /** Format: date-time */
            updated_at: string;
        };
        StockMovementInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StockMovementInput.json
             */
            readonly $schema?: string;
            note?: string;
            quantity: string;
        };
        Subject: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Subject.json
             */
            readonly $schema?: string;
            bank_account: string;
            city: string;
            country: string;
            /** Format: date-time */
            created_at: string;
            custom_id?: string;
            /** Format: int64 */
            default_due: number;
            default_payment_method: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            email: string;
            iban: string;
            /** Format: int64 */
            id: number;
            local_vat_no: string;
            name: string;
            note: string;
            phone: string;
            registration_no: string;
            street: string;
            type: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            user_id?: number;
            vat_no: string;
            website: string;
            zip: string;
        };
        SubjectInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SubjectInput.json
             */
            readonly $schema?: string;
            bank_account?: string;
            city?: string;
            country?: string;
            custom_id?: string;
            /** Format: int64 */
            default_due?: number;
            default_payment_method?: string;
            email?: string;
            iban?: string;
            local_vat_no?: string;
            name: string;
            note?: string;
            phone?: string;
            registration_no?: string;
            street?: string;
            type?: string;
            vat_no?: string;
            website?: string;
            zip?: string;
        };
        UpdateUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateUserInputBody.json
             */
            readonly $schema?: string;
            email?: string;
            is_active?: boolean;
            role?: string;
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/User.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            deleted_at?: components["schemas"]["DeletedAt"];
            email?: string;
            /** Format: int64 */
            id: number;
            is_active: boolean;
            role: string;
            /** Format: date-time */
            updated_at: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-ares-subject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description IČO (8 číslic) */
                ic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lookup"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-invoice": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID faktury */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-invoice": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID faktury */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "duplicate-invoice": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID faktury k duplikaci */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-invoice-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID faktury */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchStatusInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-price-items": {
        parameters: {
            query?: {
                /** @description Zahrnout archivované položky */
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceItemOut"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-price-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceItemInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceItemOut"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-price-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID ceníkové položky */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceItemOut"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-price-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceItemInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceItemOut"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "archive-price-item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-stock-movements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID ceníkové položky */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-stock-movement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockMovementInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-number-formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NumberFormat"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-number-format": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NumberFormatInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NumberFormat"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-number-format": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID číselné řady */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NumberFormatInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NumberFormat"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-number-format": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID číselné řady */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "next-number-format": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID číselné řady */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextFormatOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-subject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-subject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID kontaktu */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-subject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID kontaktu */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-subject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID kontaktu */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID uživatele */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID uživatele */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID uživatele */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID uživatele */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
