package api_test

import (
	"fmt"
	"net/http"
	"testing"

	"github.com/qwerin/nanofaktura/internal/api"
)

func TestInvoiceListSumsAndFilters(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")
	subj := newSubject(a, api.SubjectCreate{Name: "ACME"})
	mk := func(price int64, cur string) api.Invoice {
		b := api.InvoiceCreate{SubjectID: subj.ID, Lines: []api.InvoiceLineInput{line("A", "1", price, nil)}}
		if cur != "" {
			b.Currency, b.ExchangeRate = cur, "25"
		}
		return createInv(a, b)
	}
	mk(1000, "")
	i2 := mk(2000, "")
	mk(500, "EUR")
	cancelled := mk(700, "")
	action(a, cancelled.ID, "cancel")
	pay(a, i2.ID, api.PaymentCreate{Amount: i64(500)})
	createInv(a, api.InvoiceCreate{SubjectID: subj.ID, IssuedOn: "2026-01-01", DueDays: intPtr(1),
		Lines: []api.InvoiceLineInput{line("A", "1", 300, nil)}})

	l := doJSON[api.DocumentList[api.InvoiceSummary]](a, http.StatusOK, "GET", a.acct("/invoices?per_page=1"), nil)
	if l.Total != 5 || len(l.Items) != 1 || len(l.Sums) != 2 {
		t.Fatalf("list %+v", l)
	}
	if czk := l.Sums[0]; czk.Currency != "CZK" || czk.Count != 4 || czk.SumTotal != 4000 || czk.SumRemaining != 1000+1500+300 {
		t.Fatalf("czk %+v", czk)
	}
	if eur := l.Sums[1]; eur.Currency != "EUR" || eur.SumTotal != 500 || eur.SumRemaining != 500 {
		t.Fatalf("eur %+v", eur)
	}

	u := doJSON[api.DocumentList[api.InvoiceSummary]](a, http.StatusOK, "GET", a.acct("/invoices?status=unpaid"), nil)
	if u.Total != 4 { // open, partly paid, EUR, overdue
		t.Fatalf("unpaid %+v", numbers(u.ListResponse))
	}
	m := doJSON[api.DocumentList[api.InvoiceSummary]](a, http.StatusOK, "GET", a.acct("/invoices?status=overdue,cancelled"), nil)
	if m.Total != 2 {
		t.Fatalf("multi %+v", numbers(m.ListResponse))
	}
	res, body := a.do("GET", a.acct("/invoices?status=bogus"), nil)
	assertCode(t, res, body, http.StatusUnprocessableEntity, "validation_failed")

	// amount matches the total or the remaining amount
	am := doJSON[api.DocumentList[api.InvoiceSummary]](a, http.StatusOK, "GET", a.acct("/invoices?amount=1500"), nil)
	if am.Total != 1 || am.Items[0].ID != i2.ID {
		t.Fatalf("amount %+v", numbers(am.ListResponse))
	}

	// recurring_id: invoices generated by a recurring invoice
	tpl := newTemplate(a, subj.ID, "Hosting")
	rec := newRecurring(a, api.RecurringCreate{Name: "R", TemplateID: tpl.ID})
	if err := runJob(ts, "recurring"); err != nil {
		t.Fatal(err)
	}
	r := doJSON[api.DocumentList[api.InvoiceSummary]](a, http.StatusOK, "GET", a.acct(fmt.Sprintf("/invoices?recurring_id=%d", rec.ID)), nil)
	if r.Total != 1 || r.Items[0].RecurringID == nil || *r.Items[0].RecurringID != rec.ID {
		t.Fatalf("recurring %+v", r)
	}
}

func TestExpenseListSumsAndFilters(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")
	name := "Dodavatel"
	mk := func(price int64) api.Expense {
		return createExp(a, api.ExpenseCreate{ExpenseSupplierFields: api.ExpenseSupplierFields{SupplierName: &name},
			Lines: []api.InvoiceLineInput{line("x", "1", price, i32(0))}})
	}
	mk(1000)
	e2 := mk(2000)
	a.mustDo(http.StatusCreated, "POST", expURL(a, e2.ID, "/payments"), map[string]any{"amount": 2000})
	l := doJSON[api.DocumentList[api.ExpenseSummary]](a, http.StatusOK, "GET", a.acct("/expenses"), nil)
	if l.Total != 2 || len(l.Sums) != 1 || l.Sums[0].SumTotal != 3000 || l.Sums[0].SumRemaining != 1000 {
		t.Fatalf("sums %+v", l)
	}
	u := doJSON[api.DocumentList[api.ExpenseSummary]](a, http.StatusOK, "GET", a.acct("/expenses?status=unpaid&amount=1000"), nil)
	if u.Total != 1 || u.Sums[0].SumTotal != 1000 {
		t.Fatalf("unpaid %+v", u)
	}
}
