package api

import (
	"slices"
	"strings"

	"github.com/danielgtaylor/huma/v2"
	"gorm.io/gorm"

	"github.com/qwerin/nanofaktura/internal/billing"
	"github.com/qwerin/nanofaktura/internal/model"
)

// StatusUnpaid is the pseudo status of the list filters: every document
// still waiting for payment (invoices open + sent + overdue, expenses open +
// overdue).
const StatusUnpaid = "unpaid"

var (
	invoiceFilterStatuses = []string{model.StatusOpen, model.StatusSent, billing.StatusOverdue, model.StatusPaid,
		model.StatusCancelled, model.StatusUncollectible, StatusUnpaid}
	expenseFilterStatuses = []string{model.StatusOpen, billing.StatusOverdue, model.StatusPaid, StatusUnpaid}
)

// splitStatuses parses a comma-separated status filter.
func splitStatuses(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if p = strings.TrimSpace(p); p != "" && !slices.Contains(out, p) {
			out = append(out, p)
		}
	}
	return out
}

// checkStatuses validates a comma-separated status filter.
func checkStatuses(s string, allowed []string) []error {
	for _, st := range splitStatuses(s) {
		if !slices.Contains(allowed, st) {
			return []error{&huma.ErrorDetail{Location: "query.status", Value: st,
				Message: "unknown status; allowed: " + strings.Join(allowed, ", ")}}
		}
	}
	return nil
}

// orConditions ORs (sql, args) pairs into one parenthesised WHERE.
func orConditions(q *gorm.DB, conds [][]any) *gorm.DB {
	if len(conds) == 0 {
		return q
	}
	sqls := make([]string, len(conds))
	var args []any
	for i, c := range conds {
		sqls[i] = "(" + c[0].(string) + ")"
		args = append(args, c[1:]...)
	}
	return q.Where("("+strings.Join(sqls, " OR ")+")", args...)
}

// InvoiceFilter are the query parameters shared by the invoice list and the
// invoice exports (CSV, XLSX, PDF ZIP), so an export contains exactly what
// the list shows.
type InvoiceFilter struct {
	Status       string `query:"status" example:"unpaid" doc:"Effective status, comma-separated for several: open, sent, overdue, paid, cancelled, uncollectible, unpaid (= open + sent + overdue). open/sent exclude overdue documents"`
	DocumentType string `query:"document_type" enum:"invoice,proforma,correction,tax_document"`
	SubjectID    uint   `query:"subject_id"`
	RecurringID  uint   `query:"recurring_id" doc:"Documents generated by this recurring invoice"`
	Amount       int64  `query:"amount" doc:"Total or remaining amount equals this value (minor units; manual payment matching)"`
	Since        string `query:"since" format:"date" doc:"issued_on ≥ since"`
	Until        string `query:"until" format:"date" doc:"issued_on ≤ until"`
	Query        string `query:"query" doc:"Number, client name or variable symbol (case-insensitive substring)"`
	Sort         string `query:"sort" enum:"-issued_on,issued_on,-number,due_on,-total" default:"-issued_on"`
}

// Resolve validates the status list (huma calls it before the handler).
func (f *InvoiceFilter) Resolve(huma.Context) []error {
	return checkStatuses(f.Status, invoiceFilterStatuses)
}

var invoiceSorts = map[string]string{
	"-issued_on": "issued_on DESC, id DESC",
	"issued_on":  "issued_on, id",
	"-number":    "number DESC, id DESC",
	"due_on":     "due_on, id",
	"-total":     "total DESC, id DESC",
}

// query applies the filter and the ordering to q (already scoped to the
// account); today decides what is overdue.
func (f *InvoiceFilter) query(q *gorm.DB, today string) *gorm.DB {
	order, ok := invoiceSorts[f.Sort]
	if !ok {
		order = invoiceSorts["-issued_on"]
	}
	return f.where(q, today).Order(order)
}

// where applies the filter without ordering (list sums group the result).
func (f *InvoiceFilter) where(q *gorm.DB, today string) *gorm.DB {
	q = q.Model(&model.Invoice{})
	var conds [][]any
	for _, st := range splitStatuses(f.Status) {
		switch st {
		case StatusUnpaid:
			conds = append(conds, []any{"status IN ?", []string{model.StatusOpen, model.StatusSent}})
		case billing.StatusOverdue:
			conds = append(conds, []any{"status IN ? AND due_on <> '' AND due_on < ?", []string{model.StatusOpen, model.StatusSent}, today})
		case model.StatusOpen, model.StatusSent:
			conds = append(conds, []any{"status = ? AND (due_on = '' OR due_on >= ?)", st, today})
		default:
			conds = append(conds, []any{"status = ?", st})
		}
	}
	q = orConditions(q, conds)
	if f.DocumentType != "" {
		q = q.Where("document_type = ?", f.DocumentType)
	}
	if f.SubjectID != 0 {
		q = q.Where("subject_id = ?", f.SubjectID)
	}
	if f.RecurringID != 0 {
		q = q.Where("recurring_id = ?", f.RecurringID)
	}
	if f.Amount != 0 {
		q = q.Where("(total = ? OR total - paid_amount = ?)", f.Amount, f.Amount)
	}
	if f.Since != "" {
		q = q.Where("issued_on >= ?", f.Since)
	}
	if f.Until != "" {
		q = q.Where("issued_on <= ?", f.Until)
	}
	if qs := strings.TrimSpace(f.Query); qs != "" {
		like := likePattern(qs)
		q = q.Where(`(LOWER(number) LIKE ? ESCAPE '\' OR LOWER(client_name) LIKE ? ESCAPE '\' OR variable_symbol LIKE ? ESCAPE '\')`, like, like, like)
	}
	return q
}

// SubjectFilter are the query parameters shared by the subject list and the
// subject exports.
type SubjectFilter struct {
	Query string `query:"query" doc:"Case-insensitive search in name, IČO and email"`
	Type  string `query:"type" enum:"customer,supplier,both" doc:"customer/supplier also match subjects of type both"`
}

// query applies the filter and the ordering to q (already scoped to the account).
func (f *SubjectFilter) query(q *gorm.DB) *gorm.DB {
	q = q.Model(&model.Subject{}).Order("LOWER(name), id")
	if qs := strings.TrimSpace(f.Query); qs != "" {
		like := likePattern(qs)
		q = q.Where(`(LOWER(name) LIKE ? ESCAPE '\' OR registration_no LIKE ? ESCAPE '\' OR LOWER(email) LIKE ? ESCAPE '\')`, like, like, like)
	}
	switch f.Type {
	case model.SubjectCustomer, model.SubjectSupplier:
		q = q.Where("type IN ?", []string{f.Type, model.SubjectBoth})
	case model.SubjectBoth:
		q = q.Where("type = ?", model.SubjectBoth)
	}
	return q
}

// ExpenseFilter are the query parameters shared by the expense list and the
// expense exports.
type ExpenseFilter struct {
	Status    string `query:"status" example:"unpaid" doc:"Effective status, comma-separated for several: open, overdue, paid, unpaid (= open + overdue). open excludes overdue expenses"`
	Category  string `query:"category" doc:"Exact category"`
	SubjectID uint   `query:"subject_id"`
	Amount    int64  `query:"amount" doc:"Total or remaining amount equals this value (minor units; manual payment matching)"`
	Since     string `query:"since" format:"date" doc:"issued_on ≥ since"`
	Until     string `query:"until" format:"date" doc:"issued_on ≤ until"`
	Query     string `query:"query" doc:"Number, original number, supplier name, variable symbol or description (case-insensitive substring)"`
	Sort      string `query:"sort" enum:"-issued_on,issued_on,-number,due_on,-total" default:"-issued_on"`
}

// Resolve validates the status list (huma calls it before the handler).
func (f *ExpenseFilter) Resolve(huma.Context) []error {
	return checkStatuses(f.Status, expenseFilterStatuses)
}

var expenseSorts = map[string]string{
	"-issued_on": "issued_on DESC, id DESC",
	"issued_on":  "issued_on, id",
	"-number":    "number DESC, id DESC",
	"due_on":     "due_on, id",
	"-total":     "total DESC, id DESC",
}

// query applies the filter and the ordering to q (already scoped to the
// account); today decides what is overdue.
func (f *ExpenseFilter) query(q *gorm.DB, today string) *gorm.DB {
	order, ok := expenseSorts[f.Sort]
	if !ok {
		order = expenseSorts["-issued_on"]
	}
	return f.where(q, today).Order(order)
}

// where applies the filter without ordering (list sums group the result).
func (f *ExpenseFilter) where(q *gorm.DB, today string) *gorm.DB {
	q = q.Model(&model.Expense{})
	var conds [][]any
	for _, st := range splitStatuses(f.Status) {
		switch st {
		case StatusUnpaid:
			conds = append(conds, []any{"status = ?", model.StatusOpen})
		case billing.StatusOverdue:
			conds = append(conds, []any{"status = ? AND due_on <> '' AND due_on < ?", model.StatusOpen, today})
		case model.StatusOpen:
			conds = append(conds, []any{"status = ? AND (due_on = '' OR due_on >= ?)", model.StatusOpen, today})
		default:
			conds = append(conds, []any{"status = ?", st})
		}
	}
	q = orConditions(q, conds)
	if f.Category != "" {
		q = q.Where("category = ?", f.Category)
	}
	if f.SubjectID != 0 {
		q = q.Where("subject_id = ?", f.SubjectID)
	}
	if f.Amount != 0 {
		q = q.Where("(total = ? OR total - paid_amount = ?)", f.Amount, f.Amount)
	}
	if f.Since != "" {
		q = q.Where("issued_on >= ?", f.Since)
	}
	if f.Until != "" {
		q = q.Where("issued_on <= ?", f.Until)
	}
	if qs := strings.TrimSpace(f.Query); qs != "" {
		like := likePattern(qs)
		q = q.Where(`(LOWER(number) LIKE ? ESCAPE '\' OR LOWER(original_number) LIKE ? ESCAPE '\' OR LOWER(supplier_name) LIKE ? ESCAPE '\'`+
			` OR variable_symbol LIKE ? ESCAPE '\' OR LOWER(description) LIKE ? ESCAPE '\')`, like, like, like, like, like)
	}
	return q
}

// CurrencySum sums the documents of one currency matching a list filter.
type CurrencySum struct {
	Currency     string `json:"currency" example:"CZK"`
	Count        int64  `json:"count"`
	SumTotal     int64  `json:"sum_total" doc:"Σ total (minor units)"`
	SumRemaining int64  `json:"sum_remaining" doc:"Σ (total − paid) of unpaid (open/sent) documents; overpayments of paid documents are not netted"`
}

// DocumentList is a list page plus sums over the whole filter (all pages).
type DocumentList[T any] struct {
	ListResponse[T]
	Sums []CurrencySum `json:"sums" nullable:"false" doc:"Per currency, over every page of the filter"`
}

// currencySums sums total and remaining per currency over q (filtered, not ordered).
func currencySums(q *gorm.DB) ([]CurrencySum, error) {
	out := []CurrencySum{}
	err := q.Session(&gorm.Session{}).
		Select(`currency, COUNT(*) AS count, COALESCE(SUM(total), 0) AS sum_total,
			COALESCE(SUM(CASE WHEN status IN ? THEN total - paid_amount ELSE 0 END), 0) AS sum_remaining`,
			[]string{model.StatusOpen, model.StatusSent}).
		Group("currency").Order("currency").Scan(&out).Error
	if err != nil {
		return nil, dbErr(err, "sums")
	}
	return out, nil
}
