package api_test

import (
	"fmt"
	"net/http"
	"testing"

	"github.com/qwerin/nanofaktura/internal/api"
)

// ---- helpers ----

func piURL(c *client, id uint, suffix string) string {
	return fmt.Sprintf("%s/%d%s", c.acct("/price-items"), id, suffix)
}

func newPriceItem(c *client, body api.PriceItemCreate) api.PriceItem {
	c.ts.t.Helper()
	return doJSON[api.PriceItem](c, http.StatusCreated, "POST", c.acct("/price-items"), body)
}

func getPI(c *client, id uint) api.PriceItem {
	c.ts.t.Helper()
	return doJSON[api.PriceItem](c, http.StatusOK, "GET", piURL(c, id, ""), nil)
}

func listPI(c *client, query string) api.ListResponse[api.PriceItem] {
	c.ts.t.Helper()
	return doJSON[api.ListResponse[api.PriceItem]](c, http.StatusOK, "GET", c.acct("/price-items")+query, nil)
}

func piNames(l api.ListResponse[api.PriceItem]) string {
	out := []string{}
	for _, i := range l.Items {
		out = append(out, i.Name)
	}
	return fmt.Sprint(out)
}

func stockMoves(c *client, itemID uint) []api.StockMove {
	c.ts.t.Helper()
	return doJSON[api.ListResponse[api.StockMove]](c, http.StatusOK, "GET", piURL(c, itemID, "/stock-moves?per_page=200"), nil).Items
}

// assertStock checks the item's stock_quantity and that it equals Σ moves.
func assertStock(t *testing.T, c *client, itemID uint, want string) {
	t.Helper()
	item := getPI(c, itemID)
	if item.StockQuantity != want {
		t.Fatalf("stock %s, want %s", item.StockQuantity, want)
	}
	var sum float64
	for _, m := range stockMoves(c, itemID) {
		var q float64
		fmt.Sscan(m.Quantity, &q)
		if m.Direction == "out" {
			q = -q
		}
		sum += q
	}
	if got := fmt.Sprint(sum); got != want {
		t.Fatalf("Σ moves %s ≠ stock %s", got, want)
	}
}

// invoiceMove returns the only stock move of item generated by invoice invID.
func invoiceMove(t *testing.T, c *client, itemID, invID uint) api.StockMove {
	t.Helper()
	var found []api.StockMove
	for _, m := range stockMoves(c, itemID) {
		if m.InvoiceID != nil && *m.InvoiceID == invID {
			found = append(found, m)
		}
	}
	if len(found) != 1 {
		t.Fatalf("moves of invoice %d: %+v", invID, found)
	}
	return found[0]
}

// ---- price items ----

func TestPriceItemsCRUD(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")

	hosting := newPriceItem(a, api.PriceItemCreate{Name: " Hosting ", SKU: "HOST-1", UnitName: "měs", UnitPrice: 50000, Note: "n"})
	if hosting.Name != "Hosting" || hosting.SKU != "HOST-1" || hosting.UnitName != "měs" || hosting.UnitPrice != 50000 ||
		hosting.VatRateBps != 2100 || hosting.Currency != "CZK" || hosting.TrackStock || hosting.StockQuantity != "0" ||
		hosting.MinStock != "" || hosting.LowStock || hosting.Archived || hosting.ArchivedAt != nil || hosting.Note != "n" {
		t.Fatalf("defaults: %+v", hosting)
	}
	cable := newPriceItem(a, api.PriceItemCreate{Name: "Kabel UTP", SKU: "CAB-5", UnitPrice: 1990, VatRateBps: i32(1200),
		PricesIncludeVat: true, Currency: "EUR", TrackStock: true, StockQuantity: "10,5", MinStock: "3"})
	if cable.VatRateBps != 1200 || !cable.PricesIncludeVat || cable.Currency != "EUR" || !cable.TrackStock ||
		cable.StockQuantity != "10.5" || cable.MinStock != "3" || cable.LowStock {
		t.Fatalf("cable: %+v", cable)
	}
	if mv := stockMoves(a, cable.ID); len(mv) != 1 || mv[0].Direction != "in" || mv[0].Quantity != "10.5" ||
		mv[0].MovedOn != "2026-03-15" || mv[0].Note != "Počáteční stav" || mv[0].InvoiceID != nil {
		t.Fatalf("initial move: %+v", mv)
	}
	newPriceItem(a, api.PriceItemCreate{Name: "Adaptér", SKU: "ADP"})

	// validation
	for _, c := range []struct {
		body  api.PriceItemCreate
		field string
	}{
		{api.PriceItemCreate{Name: "  "}, "body.name"},
		{api.PriceItemCreate{Name: "X", StockQuantity: "5"}, "body.stock_quantity"},
		{api.PriceItemCreate{Name: "X", TrackStock: true, StockQuantity: "abc"}, "body.stock_quantity"},
		{api.PriceItemCreate{Name: "X", MinStock: "1.2345"}, "body.min_stock"},
		{api.PriceItemCreate{Name: "X", Currency: "czk"}, "body.currency"},
	} {
		res, body := a.do("POST", a.acct("/price-items"), c.body)
		assertError(t, res, body, http.StatusUnprocessableEntity, c.field)
	}

	// list: sorted by name, query on name and SKU
	if l := listPI(a, ""); piNames(l) != "[Adaptér Hosting Kabel UTP]" || l.Total != 3 {
		t.Fatalf("list: %s", piNames(l))
	}
	if l := listPI(a, "?query=cab"); piNames(l) != "[Kabel UTP]" {
		t.Fatalf("sku query: %s", piNames(l))
	}
	if l := listPI(a, "?query=HOST"); piNames(l) != "[Hosting]" {
		t.Fatalf("name query: %s", piNames(l))
	}
	if l := listPI(a, "?query=%25"); l.Total != 0 {
		t.Fatalf("%% must be literal: %s", piNames(l))
	}

	// patch + archive
	p := doJSON[api.PriceItem](a, http.StatusOK, "PATCH", piURL(a, hosting.ID, ""), map[string]any{
		"name": "Hosting Pro", "unit_price": 60000, "archived": true, "min_stock": "2", "track_stock": true,
	})
	if p.Name != "Hosting Pro" || p.UnitPrice != 60000 || !p.Archived || p.ArchivedAt == nil || p.MinStock != "2" ||
		!p.LowStock || p.SKU != "HOST-1" {
		t.Fatalf("patch: %+v", p)
	}
	if l := listPI(a, ""); piNames(l) != "[Adaptér Kabel UTP]" {
		t.Fatalf("active: %s", piNames(l))
	}
	if l := listPI(a, "?archived=true"); piNames(l) != "[Hosting Pro]" {
		t.Fatalf("archived: %s", piNames(l))
	}
	p = doJSON[api.PriceItem](a, http.StatusOK, "PATCH", piURL(a, hosting.ID, ""), map[string]any{"archived": false, "min_stock": ""})
	if p.Archived || p.ArchivedAt != nil || p.MinStock != "" || p.LowStock {
		t.Fatalf("unarchive: %+v", p)
	}
	res, body := a.do("PATCH", piURL(a, hosting.ID, ""), map[string]any{"name": " "})
	assertError(t, res, body, http.StatusUnprocessableEntity, "body.name")
	res, body = a.do("PATCH", piURL(a, hosting.ID, ""), map[string]any{"min_stock": "x"})
	assertError(t, res, body, http.StatusUnprocessableEntity, "body.min_stock")
	// stock_quantity is not patchable (unknown field is ignored, stock stays)
	a.mustDo(http.StatusOK, "PATCH", piURL(a, cable.ID, ""), map[string]any{"note": "x"})
	if g := getPI(a, cable.ID); g.StockQuantity != "10.5" || g.Note != "x" {
		t.Fatalf("stock after patch: %+v", g)
	}

	// low stock filter
	a.mustDo(http.StatusOK, "PATCH", piURL(a, cable.ID, ""), map[string]any{"min_stock": "10.5"})
	if l := listPI(a, "?low_stock=true"); piNames(l) != "[Kabel UTP]" || !l.Items[0].LowStock {
		t.Fatalf("low stock: %+v", l)
	}

	// delete
	a.mustDo(http.StatusNoContent, "DELETE", piURL(a, cable.ID, ""), nil)
	res, body = a.do("GET", piURL(a, cable.ID, ""), nil)
	assertError(t, res, body, http.StatusNotFound, "price item not found")
	res, body = a.do("DELETE", piURL(a, cable.ID, ""), nil)
	assertError(t, res, body, http.StatusNotFound, "price item not found")
}

func TestStockMovesManual(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")
	item := newPriceItem(a, api.PriceItemCreate{Name: "Myš", TrackStock: true, MinStock: "5"})
	if !item.LowStock {
		t.Fatalf("0 ≤ 5 must be low: %+v", item)
	}

	r := doJSON[api.StockMoveResult](a, http.StatusCreated, "POST", piURL(a, item.ID, "/stock-moves"),
		api.StockMoveCreate{Direction: "in", Quantity: "10", MovedOn: "2026-03-01", Note: "příjem"})
	if r.Move.Direction != "in" || r.Move.Quantity != "10" || r.Move.MovedOn != "2026-03-01" || r.Move.Note != "příjem" ||
		r.Move.PriceItemID != item.ID || r.PriceItem.StockQuantity != "10" || r.PriceItem.LowStock {
		t.Fatalf("in: %+v", r)
	}
	out := doJSON[api.StockMoveResult](a, http.StatusCreated, "POST", piURL(a, item.ID, "/stock-moves"),
		api.StockMoveCreate{Direction: "out", Quantity: "6.25"})
	if out.Move.MovedOn != "2026-03-15" || out.PriceItem.StockQuantity != "3.75" || !out.PriceItem.LowStock {
		t.Fatalf("out: %+v", out)
	}
	// newest first
	if mv := stockMoves(a, item.ID); len(mv) != 2 || mv[0].ID != out.Move.ID {
		t.Fatalf("moves: %+v", mv)
	}
	// stock may go negative
	doJSON[api.StockMoveResult](a, http.StatusCreated, "POST", piURL(a, item.ID, "/stock-moves"),
		api.StockMoveCreate{Direction: "out", Quantity: "5"})
	assertStock(t, a, item.ID, "-1.25")

	for _, c := range []struct {
		body  api.StockMoveCreate
		field string
	}{
		{api.StockMoveCreate{Direction: "in", Quantity: "0"}, "body.quantity"},
		{api.StockMoveCreate{Direction: "in", Quantity: "-1"}, "body.quantity"},
		{api.StockMoveCreate{Direction: "in", Quantity: "x"}, "body.quantity"},
		{api.StockMoveCreate{Direction: "sideways", Quantity: "1"}, "body.direction"},
		{api.StockMoveCreate{Direction: "in", Quantity: "1", MovedOn: "2026-02-30"}, "moved_on"},
	} {
		res, body := a.do("POST", piURL(a, item.ID, "/stock-moves"), c.body)
		assertError(t, res, body, http.StatusUnprocessableEntity, c.field)
	}

	// untracked item → 409
	plain := newPriceItem(a, api.PriceItemCreate{Name: "Služba"})
	res, body := a.do("POST", piURL(a, plain.ID, "/stock-moves"), api.StockMoveCreate{Direction: "in", Quantity: "1"})
	assertError(t, res, body, http.StatusConflict, "track_stock")

	// delete a manual move reverts it; a move of another item → 404
	res, body = a.do("DELETE", piURL(a, plain.ID, fmt.Sprintf("/stock-moves/%d", out.Move.ID)), nil)
	assertError(t, res, body, http.StatusNotFound, "stock move not found")
	a.mustDo(http.StatusNoContent, "DELETE", piURL(a, item.ID, fmt.Sprintf("/stock-moves/%d", out.Move.ID)), nil)
	assertStock(t, a, item.ID, "5")
	res, body = a.do("GET", piURL(a, 999, "/stock-moves"), nil)
	assertError(t, res, body, http.StatusNotFound, "price item not found")
}

func TestPriceItemsTenantIsolation(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")
	b := ts.signup("b@example.cz", "Firma B")
	item := newPriceItem(a, api.PriceItemCreate{Name: "Myš", TrackStock: true, StockQuantity: "4"})
	mv := stockMoves(a, item.ID)[0]

	for _, r := range []struct {
		method, suffix string
		body           any
	}{
		{"GET", "", nil},
		{"PATCH", "", map[string]any{"name": "x"}},
		{"DELETE", "", nil},
		{"GET", "/stock-moves", nil},
		{"POST", "/stock-moves", api.StockMoveCreate{Direction: "in", Quantity: "1"}},
		{"DELETE", fmt.Sprintf("/stock-moves/%d", mv.ID), nil},
	} {
		res, body := b.do(r.method, piURL(b, item.ID, r.suffix), r.body)
		assertError(t, res, body, http.StatusNotFound, "not found")
		res, body = b.do(r.method, piURL(a, item.ID, r.suffix), r.body)
		assertError(t, res, body, http.StatusNotFound, "not found")
	}
	if l := listPI(b, ""); l.Total != 0 {
		t.Fatalf("b sees items: %+v", l)
	}
	if g := getPI(a, item.ID); g.Name != "Myš" || g.StockQuantity != "4" {
		t.Fatalf("a's item changed: %+v", g)
	}

	// b cannot reference a's price item on its documents
	bs := newSubject(b, api.SubjectCreate{Name: "B"})
	l := line("X", "1", 100, nil)
	l.PriceItemID = &item.ID
	res, body := b.do("POST", b.acct("/invoices"), api.InvoiceCreate{SubjectID: new(bs.ID), Lines: []api.InvoiceLineInput{l}})
	assertError(t, res, body, http.StatusUnprocessableEntity, "lines[0].price_item_id")
	res, body = b.do("POST", b.acct("/expenses"), api.ExpenseCreate{ExpenseSupplierFields: api.ExpenseSupplierFields{SupplierName: &bs.Name}, Lines: []api.InvoiceLineInput{l}})
	assertError(t, res, body, http.StatusUnprocessableEntity, "lines[0].price_item_id")
	assertStock(t, a, item.ID, "4")
}

// ---- stock consistency with documents ----

func TestInvoiceStock(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")
	subj := newSubject(a, api.SubjectCreate{Name: "ACME"})
	tracked := newPriceItem(a, api.PriceItemCreate{Name: "Myš", TrackStock: true, StockQuantity: "10"})
	plain := newPriceItem(a, api.PriceItemCreate{Name: "Montáž"})
	itemLine := func(id uint, qty string) api.InvoiceLineInput {
		l := line("X", qty, 100, nil)
		l.PriceItemID = &id
		return l
	}

	// create: tracked line moves out, untracked and unlinked lines do not
	inv := createInv(a, api.InvoiceCreate{SubjectID: new(subj.ID), IssuedOn: "2026-03-10", Lines: []api.InvoiceLineInput{
		itemLine(tracked.ID, "2"), itemLine(plain.ID, "1"), line("Doprava", "1", 100, nil),
	}})
	if inv.Lines[0].PriceItemID == nil || *inv.Lines[0].PriceItemID != tracked.ID {
		t.Fatalf("price_item_id: %+v", inv.Lines)
	}
	assertStock(t, a, tracked.ID, "8")
	mv := invoiceMove(t, a, tracked.ID, inv.ID)
	if mv.Direction != "out" || mv.Quantity != "2" || mv.MovedOn != "2026-03-10" || mv.InvoiceID == nil || *mv.InvoiceID != inv.ID {
		t.Fatalf("invoice move: %+v", mv)
	}
	if len(stockMoves(a, plain.ID)) != 0 {
		t.Fatal("untracked item got a move")
	}
	// generated moves cannot be deleted manually
	res, body := a.do("DELETE", piURL(a, tracked.ID, fmt.Sprintf("/stock-moves/%d", mv.ID)), nil)
	assertError(t, res, body, http.StatusConflict, "generated from a document")

	// proforma does not move stock
	pro := createInv(a, api.InvoiceCreate{DocumentType: "proforma", SubjectID: new(subj.ID), Lines: []api.InvoiceLineInput{itemLine(tracked.ID, "5")}})
	assertStock(t, a, tracked.ID, "8")

	// PATCH rewrites the moves: quantity change, line removal, re-adding
	a.mustDo(http.StatusOK, "PATCH", invURL(a, inv.ID, ""), api.InvoicePatch{Lines: []api.InvoiceLineInput{itemLine(tracked.ID, "3.5")}})
	assertStock(t, a, tracked.ID, "6.5")
	a.mustDo(http.StatusOK, "PATCH", invURL(a, inv.ID, ""), api.InvoicePatch{Lines: []api.InvoiceLineInput{line("Jiné", "1", 1, nil)}})
	assertStock(t, a, tracked.ID, "10")
	a.mustDo(http.StatusOK, "PATCH", invURL(a, inv.ID, ""), api.InvoicePatch{Lines: []api.InvoiceLineInput{itemLine(tracked.ID, "2")}})
	assertStock(t, a, tracked.ID, "8")
	// a PATCH without lines keeps the moves (moved_on follows issued_on)
	a.mustDo(http.StatusOK, "PATCH", invURL(a, inv.ID, ""), map[string]any{"issued_on": "2026-03-12"})
	assertStock(t, a, tracked.ID, "8")
	if mv := invoiceMove(t, a, tracked.ID, inv.ID); mv.MovedOn != "2026-03-12" {
		t.Fatalf("moved_on: %+v", mv)
	}
	// foreign/missing price item → 422 on PATCH too
	res, body = a.do("PATCH", invURL(a, inv.ID, ""), api.InvoicePatch{Lines: []api.InvoiceLineInput{itemLine(9999, "1")}})
	assertError(t, res, body, http.StatusUnprocessableEntity, "lines[0].price_item_id")
	assertStock(t, a, tracked.ID, "8")

	// cancel returns the goods, undo_cancel takes them again
	action(a, inv.ID, "cancel")
	assertStock(t, a, tracked.ID, "10")
	action(a, inv.ID, "undo_cancel")
	assertStock(t, a, tracked.ID, "8")
	action(a, inv.ID, "mark_as_sent") // other actions do not touch stock
	assertStock(t, a, tracked.ID, "8")

	// correction (negative quantities) returns the goods
	corr := doJSON[api.Invoice](a, http.StatusCreated, "POST", invURL(a, inv.ID, "/correction"), map[string]any{"correction_reason": "Vrácení zboží"})
	if corr.Lines[0].Quantity != "-2" || corr.Lines[0].PriceItemID == nil {
		t.Fatalf("correction lines: %+v", corr.Lines)
	}
	assertStock(t, a, tracked.ID, "10")
	if mv := invoiceMove(t, a, tracked.ID, corr.ID); mv.Direction != "in" || mv.Quantity != "2" {
		t.Fatalf("correction move: %+v", mv)
	}
	a.mustDo(http.StatusNoContent, "DELETE", invURL(a, corr.ID, ""), nil)
	assertStock(t, a, tracked.ID, "8")

	// deleting the invoice returns its goods
	a.mustDo(http.StatusNoContent, "DELETE", invURL(a, inv.ID, ""), nil)
	assertStock(t, a, tracked.ID, "10")

	// deleting a cancelled invoice does not return the goods twice
	inv2 := createInv(a, api.InvoiceCreate{SubjectID: new(subj.ID), Lines: []api.InvoiceLineInput{itemLine(tracked.ID, "1")}})
	assertStock(t, a, tracked.ID, "9")
	action(a, inv2.ID, "cancel")
	a.mustDo(http.StatusNoContent, "DELETE", invURL(a, inv2.ID, ""), nil)
	assertStock(t, a, tracked.ID, "10")

	// the final invoice created from a paid proforma moves stock out
	r := pay(a, pro.ID, api.PaymentCreate{CreateFinalInvoice: true})
	if r.FinalInvoiceID == nil {
		t.Fatal("no final invoice")
	}
	assertStock(t, a, tracked.ID, "5")

	// duplicate moves stock too
	dup := doJSON[api.Invoice](a, http.StatusCreated, "POST", invURL(a, *r.FinalInvoiceID, "/duplicate"), nil)
	assertStock(t, a, tracked.ID, "0")

	// deleting the price item unlinks the lines and drops its moves
	a.mustDo(http.StatusNoContent, "DELETE", piURL(a, tracked.ID, ""), nil)
	if g := getInv(a, dup.ID); g.Lines[0].PriceItemID != nil {
		t.Fatalf("line still linked: %+v", g.Lines[0])
	}
	a.mustDo(http.StatusNoContent, "DELETE", invURL(a, dup.ID, ""), nil) // no moves left, nothing to revert
}

func TestExpenseStock(t *testing.T) {
	ts := newTestServer(t)
	a := ts.signup("a@example.cz", "Firma A")
	item := newPriceItem(a, api.PriceItemCreate{Name: "Myš", TrackStock: true})
	l := line("Myš", "5", 100, nil)
	l.PriceItemID = &item.ID
	supplier := "Dodavatel"

	exp := createExp(a, api.ExpenseCreate{ExpenseSupplierFields: api.ExpenseSupplierFields{SupplierName: &supplier}, IssuedOn: "2026-03-01", Lines: []api.InvoiceLineInput{l}})
	assertStock(t, a, item.ID, "5")
	mv := stockMoves(a, item.ID)[0]
	if mv.Direction != "in" || mv.ExpenseID == nil || *mv.ExpenseID != exp.ID || mv.MovedOn != "2026-03-01" {
		t.Fatalf("expense move: %+v", mv)
	}
	l.Quantity = "7"
	a.mustDo(http.StatusOK, "PATCH", expURL(a, exp.ID, ""), api.ExpensePatch{Lines: []api.InvoiceLineInput{l}})
	assertStock(t, a, item.ID, "7")
	res, body := a.do("DELETE", piURL(a, item.ID, fmt.Sprintf("/stock-moves/%d", stockMoves(a, item.ID)[0].ID)), nil)
	assertError(t, res, body, http.StatusConflict, "generated from a document")
	a.mustDo(http.StatusNoContent, "DELETE", expURL(a, exp.ID, ""), nil)
	assertStock(t, a, item.ID, "0")
}
