/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ASlugRouteRouteImport } from './routes/a/$slug/route'
import { Route as ASlugIndexRouteImport } from './routes/a/$slug/index'
import { Route as ASlugDashboardRouteImport } from './routes/a/$slug/dashboard'
import { Route as ASlugSettingsRouteRouteImport } from './routes/a/$slug/settings/route'
import { Route as ASlugInvoicesIndexRouteImport } from './routes/a/$slug/invoices/index'
import { Route as ASlugInvoicesNewRouteImport } from './routes/a/$slug/invoices/new'
import { Route as ASlugSettingsIndexRouteImport } from './routes/a/$slug/settings/index'
import { Route as ASlugSettingsBankAccountsRouteImport } from './routes/a/$slug/settings/bank-accounts'
import { Route as ASlugSettingsCompanyRouteImport } from './routes/a/$slug/settings/company'
import { Route as ASlugSettingsNumberFormatsRouteImport } from './routes/a/$slug/settings/number-formats'
import { Route as ASlugSettingsProfileRouteImport } from './routes/a/$slug/settings/profile'
import { Route as ASlugSettingsTokensRouteImport } from './routes/a/$slug/settings/tokens'
import { Route as ASlugSubjectsIndexRouteImport } from './routes/a/$slug/subjects/index'
import { Route as ASlugSubjectsSubjectIdRouteImport } from './routes/a/$slug/subjects/$subjectId'
import { Route as ASlugSubjectsNewRouteImport } from './routes/a/$slug/subjects/new'
import { Route as ASlugInvoicesInvoiceIdIndexRouteImport } from './routes/a/$slug/invoices/$invoiceId/index'
import { Route as ASlugInvoicesInvoiceIdEditRouteImport } from './routes/a/$slug/invoices/$invoiceId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRouteRoute = ASlugRouteRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugIndexRoute = ASlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugDashboardRoute = ASlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSettingsRouteRoute = ASlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugInvoicesIndexRoute = ASlugInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugInvoicesNewRoute = ASlugInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSettingsIndexRoute = ASlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsBankAccountsRoute =
  ASlugSettingsBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => ASlugSettingsRouteRoute,
  } as any)
const ASlugSettingsCompanyRoute = ASlugSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsNumberFormatsRoute =
  ASlugSettingsNumberFormatsRouteImport.update({
    id: '/number-formats',
    path: '/number-formats',
    getParentRoute: () => ASlugSettingsRouteRoute,
  } as any)
const ASlugSettingsProfileRoute = ASlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsTokensRoute = ASlugSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSubjectsIndexRoute = ASlugSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSubjectsSubjectIdRoute = ASlugSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSubjectsNewRoute = ASlugSubjectsNewRouteImport.update({
  id: '/subjects/new',
  path: '/subjects/new',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugInvoicesInvoiceIdIndexRoute =
  ASlugInvoicesInvoiceIdIndexRouteImport.update({
    id: '/invoices/$invoiceId/',
    path: '/invoices/$invoiceId/',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugInvoicesInvoiceIdEditRoute =
  ASlugInvoicesInvoiceIdEditRouteImport.update({
    id: '/invoices/$invoiceId/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => ASlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/a/$slug': typeof ASlugRouteRouteWithChildren
  '/a/$slug/settings': typeof ASlugSettingsRouteRouteWithChildren
  '/a/$slug/dashboard': typeof ASlugDashboardRoute
  '/a/$slug/': typeof ASlugIndexRoute
  '/a/$slug/invoices/new': typeof ASlugInvoicesNewRoute
  '/a/$slug/settings/bank-accounts': typeof ASlugSettingsBankAccountsRoute
  '/a/$slug/settings/company': typeof ASlugSettingsCompanyRoute
  '/a/$slug/settings/number-formats': typeof ASlugSettingsNumberFormatsRoute
  '/a/$slug/settings/profile': typeof ASlugSettingsProfileRoute
  '/a/$slug/settings/tokens': typeof ASlugSettingsTokensRoute
  '/a/$slug/subjects/$subjectId': typeof ASlugSubjectsSubjectIdRoute
  '/a/$slug/subjects/new': typeof ASlugSubjectsNewRoute
  '/a/$slug/invoices/': typeof ASlugInvoicesIndexRoute
  '/a/$slug/settings/': typeof ASlugSettingsIndexRoute
  '/a/$slug/subjects/': typeof ASlugSubjectsIndexRoute
  '/a/$slug/invoices/$invoiceId/edit': typeof ASlugInvoicesInvoiceIdEditRoute
  '/a/$slug/invoices/$invoiceId/': typeof ASlugInvoicesInvoiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/a/$slug/dashboard': typeof ASlugDashboardRoute
  '/a/$slug': typeof ASlugIndexRoute
  '/a/$slug/invoices/new': typeof ASlugInvoicesNewRoute
  '/a/$slug/settings/bank-accounts': typeof ASlugSettingsBankAccountsRoute
  '/a/$slug/settings/company': typeof ASlugSettingsCompanyRoute
  '/a/$slug/settings/number-formats': typeof ASlugSettingsNumberFormatsRoute
  '/a/$slug/settings/profile': typeof ASlugSettingsProfileRoute
  '/a/$slug/settings/tokens': typeof ASlugSettingsTokensRoute
  '/a/$slug/subjects/$subjectId': typeof ASlugSubjectsSubjectIdRoute
  '/a/$slug/subjects/new': typeof ASlugSubjectsNewRoute
  '/a/$slug/invoices': typeof ASlugInvoicesIndexRoute
  '/a/$slug/settings': typeof ASlugSettingsIndexRoute
  '/a/$slug/subjects': typeof ASlugSubjectsIndexRoute
  '/a/$slug/invoices/$invoiceId/edit': typeof ASlugInvoicesInvoiceIdEditRoute
  '/a/$slug/invoices/$invoiceId': typeof ASlugInvoicesInvoiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/a/$slug': typeof ASlugRouteRouteWithChildren
  '/a/$slug/settings': typeof ASlugSettingsRouteRouteWithChildren
  '/a/$slug/dashboard': typeof ASlugDashboardRoute
  '/a/$slug/': typeof ASlugIndexRoute
  '/a/$slug/invoices/new': typeof ASlugInvoicesNewRoute
  '/a/$slug/settings/bank-accounts': typeof ASlugSettingsBankAccountsRoute
  '/a/$slug/settings/company': typeof ASlugSettingsCompanyRoute
  '/a/$slug/settings/number-formats': typeof ASlugSettingsNumberFormatsRoute
  '/a/$slug/settings/profile': typeof ASlugSettingsProfileRoute
  '/a/$slug/settings/tokens': typeof ASlugSettingsTokensRoute
  '/a/$slug/subjects/$subjectId': typeof ASlugSubjectsSubjectIdRoute
  '/a/$slug/subjects/new': typeof ASlugSubjectsNewRoute
  '/a/$slug/invoices/': typeof ASlugInvoicesIndexRoute
  '/a/$slug/settings/': typeof ASlugSettingsIndexRoute
  '/a/$slug/subjects/': typeof ASlugSubjectsIndexRoute
  '/a/$slug/invoices/$invoiceId/edit': typeof ASlugInvoicesInvoiceIdEditRoute
  '/a/$slug/invoices/$invoiceId/': typeof ASlugInvoicesInvoiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/a/$slug'
    | '/a/$slug/settings'
    | '/a/$slug/dashboard'
    | '/a/$slug/'
    | '/a/$slug/invoices/new'
    | '/a/$slug/settings/bank-accounts'
    | '/a/$slug/settings/company'
    | '/a/$slug/settings/number-formats'
    | '/a/$slug/settings/profile'
    | '/a/$slug/settings/tokens'
    | '/a/$slug/subjects/$subjectId'
    | '/a/$slug/subjects/new'
    | '/a/$slug/invoices/'
    | '/a/$slug/settings/'
    | '/a/$slug/subjects/'
    | '/a/$slug/invoices/$invoiceId/edit'
    | '/a/$slug/invoices/$invoiceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/a/$slug/dashboard'
    | '/a/$slug'
    | '/a/$slug/invoices/new'
    | '/a/$slug/settings/bank-accounts'
    | '/a/$slug/settings/company'
    | '/a/$slug/settings/number-formats'
    | '/a/$slug/settings/profile'
    | '/a/$slug/settings/tokens'
    | '/a/$slug/subjects/$subjectId'
    | '/a/$slug/subjects/new'
    | '/a/$slug/invoices'
    | '/a/$slug/settings'
    | '/a/$slug/subjects'
    | '/a/$slug/invoices/$invoiceId/edit'
    | '/a/$slug/invoices/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/a/$slug'
    | '/a/$slug/settings'
    | '/a/$slug/dashboard'
    | '/a/$slug/'
    | '/a/$slug/invoices/new'
    | '/a/$slug/settings/bank-accounts'
    | '/a/$slug/settings/company'
    | '/a/$slug/settings/number-formats'
    | '/a/$slug/settings/profile'
    | '/a/$slug/settings/tokens'
    | '/a/$slug/subjects/$subjectId'
    | '/a/$slug/subjects/new'
    | '/a/$slug/invoices/'
    | '/a/$slug/settings/'
    | '/a/$slug/subjects/'
    | '/a/$slug/invoices/$invoiceId/edit'
    | '/a/$slug/invoices/$invoiceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ASlugRouteRoute: typeof ASlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug/': {
      id: '/a/$slug/'
      path: '/'
      fullPath: '/a/$slug/'
      preLoaderRoute: typeof ASlugIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/dashboard': {
      id: '/a/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/a/$slug/dashboard'
      preLoaderRoute: typeof ASlugDashboardRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/settings': {
      id: '/a/$slug/settings'
      path: '/settings'
      fullPath: '/a/$slug/settings'
      preLoaderRoute: typeof ASlugSettingsRouteRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/': {
      id: '/a/$slug/invoices/'
      path: '/invoices'
      fullPath: '/a/$slug/invoices/'
      preLoaderRoute: typeof ASlugInvoicesIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/new': {
      id: '/a/$slug/invoices/new'
      path: '/invoices/new'
      fullPath: '/a/$slug/invoices/new'
      preLoaderRoute: typeof ASlugInvoicesNewRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/settings/': {
      id: '/a/$slug/settings/'
      path: '/'
      fullPath: '/a/$slug/settings/'
      preLoaderRoute: typeof ASlugSettingsIndexRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/bank-accounts': {
      id: '/a/$slug/settings/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/a/$slug/settings/bank-accounts'
      preLoaderRoute: typeof ASlugSettingsBankAccountsRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/company': {
      id: '/a/$slug/settings/company'
      path: '/company'
      fullPath: '/a/$slug/settings/company'
      preLoaderRoute: typeof ASlugSettingsCompanyRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/number-formats': {
      id: '/a/$slug/settings/number-formats'
      path: '/number-formats'
      fullPath: '/a/$slug/settings/number-formats'
      preLoaderRoute: typeof ASlugSettingsNumberFormatsRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/profile': {
      id: '/a/$slug/settings/profile'
      path: '/profile'
      fullPath: '/a/$slug/settings/profile'
      preLoaderRoute: typeof ASlugSettingsProfileRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/tokens': {
      id: '/a/$slug/settings/tokens'
      path: '/tokens'
      fullPath: '/a/$slug/settings/tokens'
      preLoaderRoute: typeof ASlugSettingsTokensRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/subjects/': {
      id: '/a/$slug/subjects/'
      path: '/subjects'
      fullPath: '/a/$slug/subjects/'
      preLoaderRoute: typeof ASlugSubjectsIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/subjects/$subjectId': {
      id: '/a/$slug/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/a/$slug/subjects/$subjectId'
      preLoaderRoute: typeof ASlugSubjectsSubjectIdRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/subjects/new': {
      id: '/a/$slug/subjects/new'
      path: '/subjects/new'
      fullPath: '/a/$slug/subjects/new'
      preLoaderRoute: typeof ASlugSubjectsNewRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/$invoiceId/': {
      id: '/a/$slug/invoices/$invoiceId/'
      path: '/invoices/$invoiceId'
      fullPath: '/a/$slug/invoices/$invoiceId/'
      preLoaderRoute: typeof ASlugInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/$invoiceId/edit': {
      id: '/a/$slug/invoices/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/a/$slug/invoices/$invoiceId/edit'
      preLoaderRoute: typeof ASlugInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
  }
}

interface ASlugSettingsRouteRouteChildren {
  ASlugSettingsBankAccountsRoute: typeof ASlugSettingsBankAccountsRoute
  ASlugSettingsCompanyRoute: typeof ASlugSettingsCompanyRoute
  ASlugSettingsNumberFormatsRoute: typeof ASlugSettingsNumberFormatsRoute
  ASlugSettingsProfileRoute: typeof ASlugSettingsProfileRoute
  ASlugSettingsTokensRoute: typeof ASlugSettingsTokensRoute
  ASlugSettingsIndexRoute: typeof ASlugSettingsIndexRoute
}

const ASlugSettingsRouteRouteChildren: ASlugSettingsRouteRouteChildren = {
  ASlugSettingsBankAccountsRoute: ASlugSettingsBankAccountsRoute,
  ASlugSettingsCompanyRoute: ASlugSettingsCompanyRoute,
  ASlugSettingsNumberFormatsRoute: ASlugSettingsNumberFormatsRoute,
  ASlugSettingsProfileRoute: ASlugSettingsProfileRoute,
  ASlugSettingsTokensRoute: ASlugSettingsTokensRoute,
  ASlugSettingsIndexRoute: ASlugSettingsIndexRoute,
}

const ASlugSettingsRouteRouteWithChildren =
  ASlugSettingsRouteRoute._addFileChildren(ASlugSettingsRouteRouteChildren)

interface ASlugRouteRouteChildren {
  ASlugSettingsRouteRoute: typeof ASlugSettingsRouteRouteWithChildren
  ASlugDashboardRoute: typeof ASlugDashboardRoute
  ASlugIndexRoute: typeof ASlugIndexRoute
  ASlugInvoicesNewRoute: typeof ASlugInvoicesNewRoute
  ASlugSubjectsSubjectIdRoute: typeof ASlugSubjectsSubjectIdRoute
  ASlugSubjectsNewRoute: typeof ASlugSubjectsNewRoute
  ASlugInvoicesIndexRoute: typeof ASlugInvoicesIndexRoute
  ASlugSubjectsIndexRoute: typeof ASlugSubjectsIndexRoute
  ASlugInvoicesInvoiceIdEditRoute: typeof ASlugInvoicesInvoiceIdEditRoute
  ASlugInvoicesInvoiceIdIndexRoute: typeof ASlugInvoicesInvoiceIdIndexRoute
}

const ASlugRouteRouteChildren: ASlugRouteRouteChildren = {
  ASlugSettingsRouteRoute: ASlugSettingsRouteRouteWithChildren,
  ASlugDashboardRoute: ASlugDashboardRoute,
  ASlugIndexRoute: ASlugIndexRoute,
  ASlugInvoicesNewRoute: ASlugInvoicesNewRoute,
  ASlugSubjectsSubjectIdRoute: ASlugSubjectsSubjectIdRoute,
  ASlugSubjectsNewRoute: ASlugSubjectsNewRoute,
  ASlugInvoicesIndexRoute: ASlugInvoicesIndexRoute,
  ASlugSubjectsIndexRoute: ASlugSubjectsIndexRoute,
  ASlugInvoicesInvoiceIdEditRoute: ASlugInvoicesInvoiceIdEditRoute,
  ASlugInvoicesInvoiceIdIndexRoute: ASlugInvoicesInvoiceIdIndexRoute,
}

const ASlugRouteRouteWithChildren = ASlugRouteRoute._addFileChildren(
  ASlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ASlugRouteRoute: ASlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
