/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ASlugRouteRouteImport } from './routes/a/$slug/route'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ASlugIndexRouteImport } from './routes/a/$slug/index'
import { Route as ASlugDashboardRouteImport } from './routes/a/$slug/dashboard'
import { Route as ASlugOnboardingRouteImport } from './routes/a/$slug/onboarding'
import { Route as ASlugSettingsRouteRouteImport } from './routes/a/$slug/settings/route'
import { Route as ASlugExpensesIndexRouteImport } from './routes/a/$slug/expenses/index'
import { Route as ASlugExpensesNewRouteImport } from './routes/a/$slug/expenses/new'
import { Route as ASlugInvoicesIndexRouteImport } from './routes/a/$slug/invoices/index'
import { Route as ASlugInvoicesNewRouteImport } from './routes/a/$slug/invoices/new'
import { Route as ASlugPriceItemsIndexRouteImport } from './routes/a/$slug/price-items/index'
import { Route as ASlugPriceItemsNewRouteImport } from './routes/a/$slug/price-items/new'
import { Route as ASlugSettingsIndexRouteImport } from './routes/a/$slug/settings/index'
import { Route as ASlugSettingsAppearanceRouteImport } from './routes/a/$slug/settings/appearance'
import { Route as ASlugSettingsBankAccountsRouteImport } from './routes/a/$slug/settings/bank-accounts'
import { Route as ASlugSettingsCompanyRouteImport } from './routes/a/$slug/settings/company'
import { Route as ASlugSettingsMembersRouteImport } from './routes/a/$slug/settings/members'
import { Route as ASlugSettingsNumberFormatsRouteImport } from './routes/a/$slug/settings/number-formats'
import { Route as ASlugSettingsProfileRouteImport } from './routes/a/$slug/settings/profile'
import { Route as ASlugSettingsTokensRouteImport } from './routes/a/$slug/settings/tokens'
import { Route as ASlugSubjectsIndexRouteImport } from './routes/a/$slug/subjects/index'
import { Route as ASlugSubjectsNewRouteImport } from './routes/a/$slug/subjects/new'
import { Route as ASlugExpensesExpenseIdIndexRouteImport } from './routes/a/$slug/expenses/$expenseId/index'
import { Route as ASlugExpensesExpenseIdEditRouteImport } from './routes/a/$slug/expenses/$expenseId/edit'
import { Route as ASlugInvoicesInvoiceIdIndexRouteImport } from './routes/a/$slug/invoices/$invoiceId/index'
import { Route as ASlugInvoicesInvoiceIdEditRouteImport } from './routes/a/$slug/invoices/$invoiceId/edit'
import { Route as ASlugPriceItemsPriceItemIdIndexRouteImport } from './routes/a/$slug/price-items/$priceItemId/index'
import { Route as ASlugPriceItemsPriceItemIdEditRouteImport } from './routes/a/$slug/price-items/$priceItemId/edit'
import { Route as ASlugSubjectsSubjectIdIndexRouteImport } from './routes/a/$slug/subjects/$subjectId/index'
import { Route as ASlugSubjectsSubjectIdEditRouteImport } from './routes/a/$slug/subjects/$subjectId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRouteRoute = ASlugRouteRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugIndexRoute = ASlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugDashboardRoute = ASlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugOnboardingRoute = ASlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSettingsRouteRoute = ASlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugExpensesIndexRoute = ASlugExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugExpensesNewRoute = ASlugExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugInvoicesIndexRoute = ASlugInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugInvoicesNewRoute = ASlugInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugPriceItemsIndexRoute = ASlugPriceItemsIndexRouteImport.update({
  id: '/price-items/',
  path: '/price-items/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugPriceItemsNewRoute = ASlugPriceItemsNewRouteImport.update({
  id: '/price-items/new',
  path: '/price-items/new',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSettingsIndexRoute = ASlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsAppearanceRoute = ASlugSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsBankAccountsRoute =
  ASlugSettingsBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => ASlugSettingsRouteRoute,
  } as any)
const ASlugSettingsCompanyRoute = ASlugSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsMembersRoute = ASlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsNumberFormatsRoute =
  ASlugSettingsNumberFormatsRouteImport.update({
    id: '/number-formats',
    path: '/number-formats',
    getParentRoute: () => ASlugSettingsRouteRoute,
  } as any)
const ASlugSettingsProfileRoute = ASlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSettingsTokensRoute = ASlugSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ASlugSettingsRouteRoute,
} as any)
const ASlugSubjectsIndexRoute = ASlugSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugSubjectsNewRoute = ASlugSubjectsNewRouteImport.update({
  id: '/subjects/new',
  path: '/subjects/new',
  getParentRoute: () => ASlugRouteRoute,
} as any)
const ASlugExpensesExpenseIdIndexRoute =
  ASlugExpensesExpenseIdIndexRouteImport.update({
    id: '/expenses/$expenseId/',
    path: '/expenses/$expenseId/',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugExpensesExpenseIdEditRoute =
  ASlugExpensesExpenseIdEditRouteImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugInvoicesInvoiceIdIndexRoute =
  ASlugInvoicesInvoiceIdIndexRouteImport.update({
    id: '/invoices/$invoiceId/',
    path: '/invoices/$invoiceId/',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugInvoicesInvoiceIdEditRoute =
  ASlugInvoicesInvoiceIdEditRouteImport.update({
    id: '/invoices/$invoiceId/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugPriceItemsPriceItemIdIndexRoute =
  ASlugPriceItemsPriceItemIdIndexRouteImport.update({
    id: '/price-items/$priceItemId/',
    path: '/price-items/$priceItemId/',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugPriceItemsPriceItemIdEditRoute =
  ASlugPriceItemsPriceItemIdEditRouteImport.update({
    id: '/price-items/$priceItemId/edit',
    path: '/price-items/$priceItemId/edit',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugSubjectsSubjectIdIndexRoute =
  ASlugSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => ASlugRouteRoute,
  } as any)
const ASlugSubjectsSubjectIdEditRoute =
  ASlugSubjectsSubjectIdEditRouteImport.update({
    id: '/subjects/$subjectId/edit',
    path: '/subjects/$subjectId/edit',
    getParentRoute: () => ASlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/a/$slug': typeof ASlugRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/a/$slug/settings': typeof ASlugSettingsRouteRouteWithChildren
  '/a/$slug/dashboard': typeof ASlugDashboardRoute
  '/a/$slug/onboarding': typeof ASlugOnboardingRoute
  '/a/$slug/': typeof ASlugIndexRoute
  '/a/$slug/expenses/new': typeof ASlugExpensesNewRoute
  '/a/$slug/invoices/new': typeof ASlugInvoicesNewRoute
  '/a/$slug/price-items/new': typeof ASlugPriceItemsNewRoute
  '/a/$slug/settings/appearance': typeof ASlugSettingsAppearanceRoute
  '/a/$slug/settings/bank-accounts': typeof ASlugSettingsBankAccountsRoute
  '/a/$slug/settings/company': typeof ASlugSettingsCompanyRoute
  '/a/$slug/settings/members': typeof ASlugSettingsMembersRoute
  '/a/$slug/settings/number-formats': typeof ASlugSettingsNumberFormatsRoute
  '/a/$slug/settings/profile': typeof ASlugSettingsProfileRoute
  '/a/$slug/settings/tokens': typeof ASlugSettingsTokensRoute
  '/a/$slug/subjects/new': typeof ASlugSubjectsNewRoute
  '/a/$slug/expenses/': typeof ASlugExpensesIndexRoute
  '/a/$slug/invoices/': typeof ASlugInvoicesIndexRoute
  '/a/$slug/price-items/': typeof ASlugPriceItemsIndexRoute
  '/a/$slug/settings/': typeof ASlugSettingsIndexRoute
  '/a/$slug/subjects/': typeof ASlugSubjectsIndexRoute
  '/a/$slug/expenses/$expenseId/edit': typeof ASlugExpensesExpenseIdEditRoute
  '/a/$slug/invoices/$invoiceId/edit': typeof ASlugInvoicesInvoiceIdEditRoute
  '/a/$slug/price-items/$priceItemId/edit': typeof ASlugPriceItemsPriceItemIdEditRoute
  '/a/$slug/subjects/$subjectId/edit': typeof ASlugSubjectsSubjectIdEditRoute
  '/a/$slug/expenses/$expenseId/': typeof ASlugExpensesExpenseIdIndexRoute
  '/a/$slug/invoices/$invoiceId/': typeof ASlugInvoicesInvoiceIdIndexRoute
  '/a/$slug/price-items/$priceItemId/': typeof ASlugPriceItemsPriceItemIdIndexRoute
  '/a/$slug/subjects/$subjectId/': typeof ASlugSubjectsSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/a/$slug/dashboard': typeof ASlugDashboardRoute
  '/a/$slug/onboarding': typeof ASlugOnboardingRoute
  '/a/$slug': typeof ASlugIndexRoute
  '/a/$slug/expenses/new': typeof ASlugExpensesNewRoute
  '/a/$slug/invoices/new': typeof ASlugInvoicesNewRoute
  '/a/$slug/price-items/new': typeof ASlugPriceItemsNewRoute
  '/a/$slug/settings/appearance': typeof ASlugSettingsAppearanceRoute
  '/a/$slug/settings/bank-accounts': typeof ASlugSettingsBankAccountsRoute
  '/a/$slug/settings/company': typeof ASlugSettingsCompanyRoute
  '/a/$slug/settings/members': typeof ASlugSettingsMembersRoute
  '/a/$slug/settings/number-formats': typeof ASlugSettingsNumberFormatsRoute
  '/a/$slug/settings/profile': typeof ASlugSettingsProfileRoute
  '/a/$slug/settings/tokens': typeof ASlugSettingsTokensRoute
  '/a/$slug/subjects/new': typeof ASlugSubjectsNewRoute
  '/a/$slug/expenses': typeof ASlugExpensesIndexRoute
  '/a/$slug/invoices': typeof ASlugInvoicesIndexRoute
  '/a/$slug/price-items': typeof ASlugPriceItemsIndexRoute
  '/a/$slug/settings': typeof ASlugSettingsIndexRoute
  '/a/$slug/subjects': typeof ASlugSubjectsIndexRoute
  '/a/$slug/expenses/$expenseId/edit': typeof ASlugExpensesExpenseIdEditRoute
  '/a/$slug/invoices/$invoiceId/edit': typeof ASlugInvoicesInvoiceIdEditRoute
  '/a/$slug/price-items/$priceItemId/edit': typeof ASlugPriceItemsPriceItemIdEditRoute
  '/a/$slug/subjects/$subjectId/edit': typeof ASlugSubjectsSubjectIdEditRoute
  '/a/$slug/expenses/$expenseId': typeof ASlugExpensesExpenseIdIndexRoute
  '/a/$slug/invoices/$invoiceId': typeof ASlugInvoicesInvoiceIdIndexRoute
  '/a/$slug/price-items/$priceItemId': typeof ASlugPriceItemsPriceItemIdIndexRoute
  '/a/$slug/subjects/$subjectId': typeof ASlugSubjectsSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/a/$slug': typeof ASlugRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/a/$slug/settings': typeof ASlugSettingsRouteRouteWithChildren
  '/a/$slug/dashboard': typeof ASlugDashboardRoute
  '/a/$slug/onboarding': typeof ASlugOnboardingRoute
  '/a/$slug/': typeof ASlugIndexRoute
  '/a/$slug/expenses/new': typeof ASlugExpensesNewRoute
  '/a/$slug/invoices/new': typeof ASlugInvoicesNewRoute
  '/a/$slug/price-items/new': typeof ASlugPriceItemsNewRoute
  '/a/$slug/settings/appearance': typeof ASlugSettingsAppearanceRoute
  '/a/$slug/settings/bank-accounts': typeof ASlugSettingsBankAccountsRoute
  '/a/$slug/settings/company': typeof ASlugSettingsCompanyRoute
  '/a/$slug/settings/members': typeof ASlugSettingsMembersRoute
  '/a/$slug/settings/number-formats': typeof ASlugSettingsNumberFormatsRoute
  '/a/$slug/settings/profile': typeof ASlugSettingsProfileRoute
  '/a/$slug/settings/tokens': typeof ASlugSettingsTokensRoute
  '/a/$slug/subjects/new': typeof ASlugSubjectsNewRoute
  '/a/$slug/expenses/': typeof ASlugExpensesIndexRoute
  '/a/$slug/invoices/': typeof ASlugInvoicesIndexRoute
  '/a/$slug/price-items/': typeof ASlugPriceItemsIndexRoute
  '/a/$slug/settings/': typeof ASlugSettingsIndexRoute
  '/a/$slug/subjects/': typeof ASlugSubjectsIndexRoute
  '/a/$slug/expenses/$expenseId/edit': typeof ASlugExpensesExpenseIdEditRoute
  '/a/$slug/invoices/$invoiceId/edit': typeof ASlugInvoicesInvoiceIdEditRoute
  '/a/$slug/price-items/$priceItemId/edit': typeof ASlugPriceItemsPriceItemIdEditRoute
  '/a/$slug/subjects/$subjectId/edit': typeof ASlugSubjectsSubjectIdEditRoute
  '/a/$slug/expenses/$expenseId/': typeof ASlugExpensesExpenseIdIndexRoute
  '/a/$slug/invoices/$invoiceId/': typeof ASlugInvoicesInvoiceIdIndexRoute
  '/a/$slug/price-items/$priceItemId/': typeof ASlugPriceItemsPriceItemIdIndexRoute
  '/a/$slug/subjects/$subjectId/': typeof ASlugSubjectsSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/a/$slug'
    | '/invite/$token'
    | '/a/$slug/settings'
    | '/a/$slug/dashboard'
    | '/a/$slug/onboarding'
    | '/a/$slug/'
    | '/a/$slug/expenses/new'
    | '/a/$slug/invoices/new'
    | '/a/$slug/price-items/new'
    | '/a/$slug/settings/appearance'
    | '/a/$slug/settings/bank-accounts'
    | '/a/$slug/settings/company'
    | '/a/$slug/settings/members'
    | '/a/$slug/settings/number-formats'
    | '/a/$slug/settings/profile'
    | '/a/$slug/settings/tokens'
    | '/a/$slug/subjects/new'
    | '/a/$slug/expenses/'
    | '/a/$slug/invoices/'
    | '/a/$slug/price-items/'
    | '/a/$slug/settings/'
    | '/a/$slug/subjects/'
    | '/a/$slug/expenses/$expenseId/edit'
    | '/a/$slug/invoices/$invoiceId/edit'
    | '/a/$slug/price-items/$priceItemId/edit'
    | '/a/$slug/subjects/$subjectId/edit'
    | '/a/$slug/expenses/$expenseId/'
    | '/a/$slug/invoices/$invoiceId/'
    | '/a/$slug/price-items/$priceItemId/'
    | '/a/$slug/subjects/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/invite/$token'
    | '/a/$slug/dashboard'
    | '/a/$slug/onboarding'
    | '/a/$slug'
    | '/a/$slug/expenses/new'
    | '/a/$slug/invoices/new'
    | '/a/$slug/price-items/new'
    | '/a/$slug/settings/appearance'
    | '/a/$slug/settings/bank-accounts'
    | '/a/$slug/settings/company'
    | '/a/$slug/settings/members'
    | '/a/$slug/settings/number-formats'
    | '/a/$slug/settings/profile'
    | '/a/$slug/settings/tokens'
    | '/a/$slug/subjects/new'
    | '/a/$slug/expenses'
    | '/a/$slug/invoices'
    | '/a/$slug/price-items'
    | '/a/$slug/settings'
    | '/a/$slug/subjects'
    | '/a/$slug/expenses/$expenseId/edit'
    | '/a/$slug/invoices/$invoiceId/edit'
    | '/a/$slug/price-items/$priceItemId/edit'
    | '/a/$slug/subjects/$subjectId/edit'
    | '/a/$slug/expenses/$expenseId'
    | '/a/$slug/invoices/$invoiceId'
    | '/a/$slug/price-items/$priceItemId'
    | '/a/$slug/subjects/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/a/$slug'
    | '/invite/$token'
    | '/a/$slug/settings'
    | '/a/$slug/dashboard'
    | '/a/$slug/onboarding'
    | '/a/$slug/'
    | '/a/$slug/expenses/new'
    | '/a/$slug/invoices/new'
    | '/a/$slug/price-items/new'
    | '/a/$slug/settings/appearance'
    | '/a/$slug/settings/bank-accounts'
    | '/a/$slug/settings/company'
    | '/a/$slug/settings/members'
    | '/a/$slug/settings/number-formats'
    | '/a/$slug/settings/profile'
    | '/a/$slug/settings/tokens'
    | '/a/$slug/subjects/new'
    | '/a/$slug/expenses/'
    | '/a/$slug/invoices/'
    | '/a/$slug/price-items/'
    | '/a/$slug/settings/'
    | '/a/$slug/subjects/'
    | '/a/$slug/expenses/$expenseId/edit'
    | '/a/$slug/invoices/$invoiceId/edit'
    | '/a/$slug/price-items/$priceItemId/edit'
    | '/a/$slug/subjects/$subjectId/edit'
    | '/a/$slug/expenses/$expenseId/'
    | '/a/$slug/invoices/$invoiceId/'
    | '/a/$slug/price-items/$priceItemId/'
    | '/a/$slug/subjects/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ASlugRouteRoute: typeof ASlugRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug/': {
      id: '/a/$slug/'
      path: '/'
      fullPath: '/a/$slug/'
      preLoaderRoute: typeof ASlugIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/dashboard': {
      id: '/a/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/a/$slug/dashboard'
      preLoaderRoute: typeof ASlugDashboardRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/onboarding': {
      id: '/a/$slug/onboarding'
      path: '/onboarding'
      fullPath: '/a/$slug/onboarding'
      preLoaderRoute: typeof ASlugOnboardingRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/settings': {
      id: '/a/$slug/settings'
      path: '/settings'
      fullPath: '/a/$slug/settings'
      preLoaderRoute: typeof ASlugSettingsRouteRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/expenses/': {
      id: '/a/$slug/expenses/'
      path: '/expenses'
      fullPath: '/a/$slug/expenses/'
      preLoaderRoute: typeof ASlugExpensesIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/expenses/new': {
      id: '/a/$slug/expenses/new'
      path: '/expenses/new'
      fullPath: '/a/$slug/expenses/new'
      preLoaderRoute: typeof ASlugExpensesNewRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/': {
      id: '/a/$slug/invoices/'
      path: '/invoices'
      fullPath: '/a/$slug/invoices/'
      preLoaderRoute: typeof ASlugInvoicesIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/new': {
      id: '/a/$slug/invoices/new'
      path: '/invoices/new'
      fullPath: '/a/$slug/invoices/new'
      preLoaderRoute: typeof ASlugInvoicesNewRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/price-items/': {
      id: '/a/$slug/price-items/'
      path: '/price-items'
      fullPath: '/a/$slug/price-items/'
      preLoaderRoute: typeof ASlugPriceItemsIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/price-items/new': {
      id: '/a/$slug/price-items/new'
      path: '/price-items/new'
      fullPath: '/a/$slug/price-items/new'
      preLoaderRoute: typeof ASlugPriceItemsNewRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/settings/': {
      id: '/a/$slug/settings/'
      path: '/'
      fullPath: '/a/$slug/settings/'
      preLoaderRoute: typeof ASlugSettingsIndexRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/appearance': {
      id: '/a/$slug/settings/appearance'
      path: '/appearance'
      fullPath: '/a/$slug/settings/appearance'
      preLoaderRoute: typeof ASlugSettingsAppearanceRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/bank-accounts': {
      id: '/a/$slug/settings/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/a/$slug/settings/bank-accounts'
      preLoaderRoute: typeof ASlugSettingsBankAccountsRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/company': {
      id: '/a/$slug/settings/company'
      path: '/company'
      fullPath: '/a/$slug/settings/company'
      preLoaderRoute: typeof ASlugSettingsCompanyRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/members': {
      id: '/a/$slug/settings/members'
      path: '/members'
      fullPath: '/a/$slug/settings/members'
      preLoaderRoute: typeof ASlugSettingsMembersRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/number-formats': {
      id: '/a/$slug/settings/number-formats'
      path: '/number-formats'
      fullPath: '/a/$slug/settings/number-formats'
      preLoaderRoute: typeof ASlugSettingsNumberFormatsRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/profile': {
      id: '/a/$slug/settings/profile'
      path: '/profile'
      fullPath: '/a/$slug/settings/profile'
      preLoaderRoute: typeof ASlugSettingsProfileRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/settings/tokens': {
      id: '/a/$slug/settings/tokens'
      path: '/tokens'
      fullPath: '/a/$slug/settings/tokens'
      preLoaderRoute: typeof ASlugSettingsTokensRouteImport
      parentRoute: typeof ASlugSettingsRouteRoute
    }
    '/a/$slug/subjects/': {
      id: '/a/$slug/subjects/'
      path: '/subjects'
      fullPath: '/a/$slug/subjects/'
      preLoaderRoute: typeof ASlugSubjectsIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/subjects/new': {
      id: '/a/$slug/subjects/new'
      path: '/subjects/new'
      fullPath: '/a/$slug/subjects/new'
      preLoaderRoute: typeof ASlugSubjectsNewRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/expenses/$expenseId/': {
      id: '/a/$slug/expenses/$expenseId/'
      path: '/expenses/$expenseId'
      fullPath: '/a/$slug/expenses/$expenseId/'
      preLoaderRoute: typeof ASlugExpensesExpenseIdIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/expenses/$expenseId/edit': {
      id: '/a/$slug/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/a/$slug/expenses/$expenseId/edit'
      preLoaderRoute: typeof ASlugExpensesExpenseIdEditRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/$invoiceId/': {
      id: '/a/$slug/invoices/$invoiceId/'
      path: '/invoices/$invoiceId'
      fullPath: '/a/$slug/invoices/$invoiceId/'
      preLoaderRoute: typeof ASlugInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/invoices/$invoiceId/edit': {
      id: '/a/$slug/invoices/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/a/$slug/invoices/$invoiceId/edit'
      preLoaderRoute: typeof ASlugInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/price-items/$priceItemId/': {
      id: '/a/$slug/price-items/$priceItemId/'
      path: '/price-items/$priceItemId'
      fullPath: '/a/$slug/price-items/$priceItemId/'
      preLoaderRoute: typeof ASlugPriceItemsPriceItemIdIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/price-items/$priceItemId/edit': {
      id: '/a/$slug/price-items/$priceItemId/edit'
      path: '/price-items/$priceItemId/edit'
      fullPath: '/a/$slug/price-items/$priceItemId/edit'
      preLoaderRoute: typeof ASlugPriceItemsPriceItemIdEditRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/subjects/$subjectId/': {
      id: '/a/$slug/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/a/$slug/subjects/$subjectId/'
      preLoaderRoute: typeof ASlugSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
    '/a/$slug/subjects/$subjectId/edit': {
      id: '/a/$slug/subjects/$subjectId/edit'
      path: '/subjects/$subjectId/edit'
      fullPath: '/a/$slug/subjects/$subjectId/edit'
      preLoaderRoute: typeof ASlugSubjectsSubjectIdEditRouteImport
      parentRoute: typeof ASlugRouteRoute
    }
  }
}

interface ASlugSettingsRouteRouteChildren {
  ASlugSettingsAppearanceRoute: typeof ASlugSettingsAppearanceRoute
  ASlugSettingsBankAccountsRoute: typeof ASlugSettingsBankAccountsRoute
  ASlugSettingsCompanyRoute: typeof ASlugSettingsCompanyRoute
  ASlugSettingsMembersRoute: typeof ASlugSettingsMembersRoute
  ASlugSettingsNumberFormatsRoute: typeof ASlugSettingsNumberFormatsRoute
  ASlugSettingsProfileRoute: typeof ASlugSettingsProfileRoute
  ASlugSettingsTokensRoute: typeof ASlugSettingsTokensRoute
  ASlugSettingsIndexRoute: typeof ASlugSettingsIndexRoute
}

const ASlugSettingsRouteRouteChildren: ASlugSettingsRouteRouteChildren = {
  ASlugSettingsAppearanceRoute: ASlugSettingsAppearanceRoute,
  ASlugSettingsBankAccountsRoute: ASlugSettingsBankAccountsRoute,
  ASlugSettingsCompanyRoute: ASlugSettingsCompanyRoute,
  ASlugSettingsMembersRoute: ASlugSettingsMembersRoute,
  ASlugSettingsNumberFormatsRoute: ASlugSettingsNumberFormatsRoute,
  ASlugSettingsProfileRoute: ASlugSettingsProfileRoute,
  ASlugSettingsTokensRoute: ASlugSettingsTokensRoute,
  ASlugSettingsIndexRoute: ASlugSettingsIndexRoute,
}

const ASlugSettingsRouteRouteWithChildren =
  ASlugSettingsRouteRoute._addFileChildren(ASlugSettingsRouteRouteChildren)

interface ASlugRouteRouteChildren {
  ASlugSettingsRouteRoute: typeof ASlugSettingsRouteRouteWithChildren
  ASlugDashboardRoute: typeof ASlugDashboardRoute
  ASlugOnboardingRoute: typeof ASlugOnboardingRoute
  ASlugIndexRoute: typeof ASlugIndexRoute
  ASlugExpensesNewRoute: typeof ASlugExpensesNewRoute
  ASlugInvoicesNewRoute: typeof ASlugInvoicesNewRoute
  ASlugPriceItemsNewRoute: typeof ASlugPriceItemsNewRoute
  ASlugSubjectsNewRoute: typeof ASlugSubjectsNewRoute
  ASlugExpensesIndexRoute: typeof ASlugExpensesIndexRoute
  ASlugInvoicesIndexRoute: typeof ASlugInvoicesIndexRoute
  ASlugPriceItemsIndexRoute: typeof ASlugPriceItemsIndexRoute
  ASlugSubjectsIndexRoute: typeof ASlugSubjectsIndexRoute
  ASlugExpensesExpenseIdEditRoute: typeof ASlugExpensesExpenseIdEditRoute
  ASlugInvoicesInvoiceIdEditRoute: typeof ASlugInvoicesInvoiceIdEditRoute
  ASlugPriceItemsPriceItemIdEditRoute: typeof ASlugPriceItemsPriceItemIdEditRoute
  ASlugSubjectsSubjectIdEditRoute: typeof ASlugSubjectsSubjectIdEditRoute
  ASlugExpensesExpenseIdIndexRoute: typeof ASlugExpensesExpenseIdIndexRoute
  ASlugInvoicesInvoiceIdIndexRoute: typeof ASlugInvoicesInvoiceIdIndexRoute
  ASlugPriceItemsPriceItemIdIndexRoute: typeof ASlugPriceItemsPriceItemIdIndexRoute
  ASlugSubjectsSubjectIdIndexRoute: typeof ASlugSubjectsSubjectIdIndexRoute
}

const ASlugRouteRouteChildren: ASlugRouteRouteChildren = {
  ASlugSettingsRouteRoute: ASlugSettingsRouteRouteWithChildren,
  ASlugDashboardRoute: ASlugDashboardRoute,
  ASlugOnboardingRoute: ASlugOnboardingRoute,
  ASlugIndexRoute: ASlugIndexRoute,
  ASlugExpensesNewRoute: ASlugExpensesNewRoute,
  ASlugInvoicesNewRoute: ASlugInvoicesNewRoute,
  ASlugPriceItemsNewRoute: ASlugPriceItemsNewRoute,
  ASlugSubjectsNewRoute: ASlugSubjectsNewRoute,
  ASlugExpensesIndexRoute: ASlugExpensesIndexRoute,
  ASlugInvoicesIndexRoute: ASlugInvoicesIndexRoute,
  ASlugPriceItemsIndexRoute: ASlugPriceItemsIndexRoute,
  ASlugSubjectsIndexRoute: ASlugSubjectsIndexRoute,
  ASlugExpensesExpenseIdEditRoute: ASlugExpensesExpenseIdEditRoute,
  ASlugInvoicesInvoiceIdEditRoute: ASlugInvoicesInvoiceIdEditRoute,
  ASlugPriceItemsPriceItemIdEditRoute: ASlugPriceItemsPriceItemIdEditRoute,
  ASlugSubjectsSubjectIdEditRoute: ASlugSubjectsSubjectIdEditRoute,
  ASlugExpensesExpenseIdIndexRoute: ASlugExpensesExpenseIdIndexRoute,
  ASlugInvoicesInvoiceIdIndexRoute: ASlugInvoicesInvoiceIdIndexRoute,
  ASlugPriceItemsPriceItemIdIndexRoute: ASlugPriceItemsPriceItemIdIndexRoute,
  ASlugSubjectsSubjectIdIndexRoute: ASlugSubjectsSubjectIdIndexRoute,
}

const ASlugRouteRouteWithChildren = ASlugRouteRoute._addFileChildren(
  ASlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ASlugRouteRoute: ASlugRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
